CampusPi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mycampus import views as vs
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', vs.login),
    url(r'^mycampus/', include('mycampus.urls',namespace='mycampus')),
]

mycampus/urls.py
from django.conf.urls import url
from mycampus import views as vs

urlpatterns = [
	url(r'^login/$', vs.login,name='login'),
	url(r'^index/$', vs.index,name='index'),
	url(r'^register/$', vs.register,name='register'),
	url(r'^register_action/', vs.register_action,name='register_action'),
	url(r'^loginJudge/', vs.loginJudge,name='loginJudge'),
	url(r'^check/', vs.check,name='check'),
	url(r'^member/$', vs.member,name='member'),
	url(r'^published/$', vs.published,name='published'),
	url(r'^show_published/$', vs.show_published,name='show_published'),
	url(r'^love/$', vs.love,name='love'),
	url(r'^send_love/$', vs.send_love,name='send_love'),
	# url(r'^teasing/$', vs.teasing,name='teasing'),
	url(r'^send_teasing/$', vs.send_teasing,name='send_teasing'),
	url(r'^learn/$', vs.learn,name='learn'),
	url(r'^learn_refresh/$', vs.learn_refresh ,name='learn_refresh'),
	url(r'^send_learn/$', vs.send_learn,name='send_learn'),
	url(r'^forgotPassword/$', vs.forgotPassword,name='forgotPassword'),
	url(r'^setEmail/', vs.setEmail,name='setEmail'),
	url(r'^rePassword/$', vs.rePassword,name='rePassword'),
	url(r'^rePasswordSubmit/$', vs.rePasswordSubmit,name='rePasswordSubmit'),
	url(r'^content/$', vs.content,name='content'),
	url(r'^index1/$', vs.index1, name='index1'),
	url(r'^index_refresh/$', vs.index_refresh, name='index_refresh'),
	url(r'^test/$', vs.test , name='test'),
	url(r'^uploadImg/$', vs.uploadImg , name='uploadImg'),
	url(r'^content/(?P<new_id>[0-9]+)$', vs.content,name='content'),
	url(r'^comments_news/(?P<new_id>[0-9]+)$', vs.comments_news,name='comments_news'),
	url(r'^childcomments_news/(?P<comment_id>[0-9]+)$', vs.childcomments_news,name='childcomments_news'),
	url(r'^childcomments_learns/(?P<comment_id>[0-9]+)$', vs.childcomments_learns,name='childcomments_learns'),
	url(r'^content_learn/(?P<learn_id>[0-9]+)$', vs.content_learn,name='content_learn'),
	url(r'^user/$', vs.user,name='user'),
	url(r'^setting_information/$', vs.setting_information,name='setting_information'),
	url(r'^content_learn/(?P<new_id>[0-9]+)$', vs.content_learn,name='content_learn'),
	url(r'^cheack_name/$', vs.cheack_name ,name='cheack_name'),
	url(r'^change_user/$', vs.change_user ,name='change_user'),
	url(r'^comments_learn/(?P<learn_id>[0-9]+)$', vs.comments_learn,name='comments_learn'),
	url(r'^news_like_post/(?P<new_id>[0-9]+)$', vs.news_like_post,name='news_like_post'),
	url(r'^learns_like_post/(?P<learn_id>[0-9]+)$', vs.learns_like_post,name='learns_like_post'),
	url(r'^mypost/$', vs.mypost,name='mypost'),
	url(r'^delete_mynew/(?P<mynew_id>[0-9]+)$',vs.delete_mynew,name='delete_mynew'),
	url(r'^delete_mylearn/(?P<mylearn_id>[0-9]+)$',vs.delete_mylearn,name='delete_mylearn'),
	url(r'^search/$',vs.search,name='search'),
	url(r'login_out/$',vs.login_out ,name='login_out'),
	url(r'comment_child/$',vs.comment_child ,name='comment_child'),
]

mycampus/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	userName = models.CharField(max_length=20)
	userPicture = models.ImageField(upload_to='user_img',null=True)
	password = models.CharField(max_length=20)
	email = models.EmailField(max_length=30)
	phone = models.CharField(max_length=20)
	remark = models.CharField(max_length=30,null=True)

class News(models.Model):
	publisher_id = models.ForeignKey(User)
	publisher = models.CharField(max_length=20,null=True)
	title = models.CharField(max_length=50,null=True)
	content = models.CharField(max_length=2000,null=True)
	images = models.ImageField(upload_to='news-img',null=True)
	time = models.DateTimeField(auto_now_add=True)
	likes = models.IntegerField(default=0,null=True)
	counts = models.IntegerField(default=0,null=True)
	uid = models.CharField(max_length=20)

class News_like(models.Model):
	critisID = models.CharField(max_length=20,null=True)
	new_id = models.IntegerField(null=True)
	liked = models.IntegerField(default=0)

class Comments_News(models.Model):
	critisID = models.CharField(max_length=20,null=True)
	new_id = models.IntegerField(null=True)
	time = models.DateTimeField(auto_now_add=True)
	content = models.CharField(max_length=255,null=True)
	images = models.ImageField(upload_to='news_img',null=True)
	ifchild = models.IntegerField(default=0)

class ChildComments_News(models.Model):
	father_Comments = models.ForeignKey(Comments_News)
	critisID = models.CharField(max_length=20,null=True)
	new_id = models.IntegerField(null=True)
	comment_id = models.IntegerField(null=True)
	time = models.DateTimeField(auto_now_add=True)
	content = models.CharField(max_length=255,null=True)
	images = models.ImageField(upload_to='news_img',null=True)

class Learns(models.Model):
	publisher_id = models.ForeignKey(User)
	publisher = models.CharField(max_length=20)
	title = models.CharField(max_length=50)
	content = models.CharField(max_length=2000)
	images = models.ImageField(upload_to='learn_img',null=True)
	time = models.DateTimeField(auto_now_add=True)
	likes = models.IntegerField(default=0,null=True)
	counts = models.IntegerField(default=0,null=True)
	like = models.IntegerField(null=True)
	uid = models.CharField(max_length=20)

class Comments_Learns(models.Model):
	critisID = models.CharField(max_length=20)
	learn_id = models.IntegerField(null=True)
	time = models.DateTimeField(auto_now_add=True)
	content = models.CharField(max_length=255)
	images = models.ImageField(upload_to='learn_img',null=True)

class ChildComments_Learns(models.Model):
	critisID = models.CharField(max_length=20,null=True)
	learn_id = models.IntegerField(null=True)
	comment_id = models.IntegerField(null=True)
	time = models.DateTimeField(auto_now_add=True)
	content = models.CharField(max_length=255,null=True)
	images = models.ImageField(upload_to='news_img',null=True)

class Learns_like(models.Model):
	critisID = models.CharField(max_length=20,null=True)
	learn_id = models.IntegerField(null=True)
	liked = models.IntegerField(default=0)
	
class Lovewall(models.Model):
	publisher = models.CharField(max_length=20)
	tosb = models.CharField(max_length=50,null=True)
	content = models.CharField(max_length=2000,null=True)
	images = models.ImageField(upload_to='learn_img',null=True)
	time = models.DateTimeField(auto_now_add=True)
	fromsb = models.CharField(max_length=20)

class Comments_Lovewall(models.Model):
	critisID = models.IntegerField()
	time = models.DateTimeField(auto_now_add=True)
	content = models.CharField(max_length=255)

class Teasingwall(models.Model):
	publisher = models.CharField(max_length=20)
	content = models.CharField(max_length=2000)
	time = models.DateTimeField(auto_now_add=True)
	images = models.ImageField(upload_to='learn_img',null=True)
	tosb = models.CharField(max_length=50)
	fromsb = models.CharField(max_length=20)

class Comments_Teasingwall(models.Model):
	critisID = models.IntegerField()
	time = models.DateTimeField(auto_now_add=True)
	content = models.CharField(max_length=255)

mycampus/views.py
#coding:utf-8
from django.shortcuts import render, render_to_response, HttpResponse, redirect, HttpResponseRedirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.mail import EmailMultiAlternatives
from . import models
import string, os, random
from PIL import Image, ImageDraw, ImageFont
from django.http import JsonResponse
import json
from django.core import serializers
from django.forms.models import model_to_dict
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def login(request):
    return render(request, 'campus/login.html')
def test(request):
    return render(request, 'campus/test.html')

def register(request):
	return render(request, 'campus/register.html')

def register_action(request):
	if request.is_ajax():
		Name = request.GET.get('Name')
		user = models.User.objects.filter(userName=Name)
		if user:
			error = "该用户已存在"
			r = HttpResponse(error)
			return r
		else:
			error = ""
			r = HttpResponse(error)
			return r 
        
	else:
		userName = request.POST.get('userName')
		password =request.POST.get('password')
		email = request.POST.get('email')
		phone =request.POST.get('phone')
		models.User.objects.create(userName=userName,password=password,email=email,phone=phone)
		return redirect('/mycampus/login/')

def loginJudge(request):
	if request.is_ajax():
		userName = request.GET.get('userName')
		password = request.GET.get('password')
		user = models.User.objects.filter(userName=userName)
		print (user)
		if len(user)==0:
			error = "用户名或密码不正确"
			r = HttpResponse(error)
			return r
		else:
			if user[0]:
				if user[0].password==password:
					error = ""
					r = HttpResponse(error)
					request.session['userId'] = user[0].id
					return r 
				else:
					error = "用户名或密码不正确"
					r = HttpResponse(error)
					return r
				error = "用户名或密码不正确"
				r = HttpResponse(error)
				return r
			else:
				error = "用户名或密码不正确"
				r = HttpResponse(error)
				return r
#主页	
def index(request):
	userId = request.session.get('userId',default=None)
	if userId:
		user = models.User.objects.get(pk=userId)
		news = models.News.objects.order_by('-id')
		news = models.News.objects.order_by('-id').filter()[0:4]
		slides = models.News.objects.filter( images__isnull=False ).order_by('-likes')[0:8]
		return render(request, 'campus/index.html',{'news':news,'user':user,'slides':slides})
	else:
		return render(request, 'campus/login.html')

	
def index1(request):
	userId = request.session.get('userId',default=None)
	user = models.User.objects.get(pk=userId)
	news = models.News.objects.order_by('-id').filter()[0:4]
	return render(request, 'campus/index1.html',{'news':news,'user':user})
# 主页下拉刷新
def index_refresh(request):
	a = int(request.GET.get('a'))
	news = models.News.objects.order_by('-id').filter()[a:a+4]
	person_list=[]
	for i in news:
		person_list.append([i.id,i.publisher,i.title,i.content,str(i.images),i.time])
	return JsonResponse(person_list,safe=False)

def member(request):
	userId = request.session.get('userId',default=None)
	if userId:
		user = models.User.objects.get(pk=userId)
		return render(request, 'campus/member.html',{'user':user})
	else:
		return render(request, 'campus/login.html')
#详细内容页面
def content(request,new_id):
	news =models.News.objects.get(pk=new_id)
	comments = models.Comments_News.objects.filter(new_id=new_id)
	childcomments = len(models.ChildComments_News.objects.filter(new_id=new_id))
	return render(request, 'campus/content.html',{'news':news,'comments':comments,'childcomments':childcomments})
#发表新闻评论
def comments_news(request,new_id):
	news =models.News.objects.get(pk=new_id)
	userId = request.session.get('userId',default=None)
	user = models.User.objects.get(pk=userId)
	content = request.POST.get('content','content')
	images = request.FILES.get('image')
	models.Comments_News.objects.create(critisID=user.userName,content=content,images=images,new_id=news.id)
	news.counts+=1
	news.save()
	comments = models.Comments_News.objects.filter(new_id=new_id)
	childcomments = len(models.ChildComments_News.objects.filter(new_id=new_id))
	return render(request, 'campus/content.html',{'news':news,'comments':comments,'childcomments':childcomments})
#发表子评论
def childcomments_news(request,comment_id):
	comment = models.Comments_News.objects.get(pk=comment_id)
	comment.ifchild=1
	comment.save()
	userId = request.session.get('userId',default=None)
	user = models.User.objects.get(pk=userId)
	content = request.POST.get('content','content')
	images = request.FILES.get('image')
	models.ChildComments_News.objects.create(father_Comments=comment,critisID=user.userName,new_id=comment.new_id,comment_id=comment_id,content=content,images=images)
	news = models.News.objects.get(id=comment.new_id)
	childcomments = len(models.ChildComments_News.objects.filter(new_id=news.id))
	comments = models.Comments_News.objects.filter(new_id=news.id)
	return render(request, 'campus/content.html',{'news':news,'comments':comments,'childcomments':childcomments})
#发表子评论
def childcomments_learns(request,comment_id):
	comment = models.Comments_Learns.objects.get(pk=comment_id)
	userId = request.session.get('userId',default=None)
	user = models.User.objects.get(pk=userId)
	content = request.POST.get('content','content')
	images = request.FILES.get('image')
	models.ChildComments_Learns.objects.create(critisID=user.userName,learn_id=comment.learn_id,comment_id=comment_id,content=content,images=images)
	learns = models.Learns.objects.get(id=comment.learn_id)
	childcomments = models.ChildComments_Learns.objects.filter(comment_id=comment_id)
	comments = models.Comments_Learns.objects.filter(pk=comment_id)
	return render(request, 'campus/content_learn.html',{'learns':learns,'comments':comments,'childcomments':childcomments})
#新闻事件点赞
def news_like_post(request,new_id):
	userId = request.session.get('userId',default=None)
	user = models.User.objects.get(pk=userId)
	news = models.News.objects.get(pk=new_id)
	like = models.News_like.objects.filter(new_id=new_id,critisID=user.userName)
	if(like):
		if(like[0].liked==1):
			news.likes-=1
			news.save()
			models.News_like.objects.filter(new_id=new_id,critisID=user.userName).update(liked=0)
		else:
			news.likes+=1
			news.save()
			models.News_like.objects.filter(new_id=new_id,critisID=user.userName).update(liked=1)
	else:
		news.likes+=1
		news.save()
		models.News_like.objects.create(critisID=user.userName,new_id=news.id,liked=1)
	comments = models.Comments_News.objects.filter(new_id=new_id)
	childcomments = models.ChildComments_News.objects.filter(new_id=new_id)
	news = models.News.objects.get(pk=new_id)
	return render(request, 'campus/content.html',{'news':news,'comments':comments,'childcomments':childcomments})
#学习事件点赞
def learns_like_post(request,learn_id):
	userId = request.session.get('userId',default=None)
	user = models.User.objects.get(pk=userId)
	learns = models.Learns.objects.get(pk=learn_id)
	like = models.Learns_like.objects.filter(learn_id=learn_id,critisID=user.userName)
	# 取消点赞
	if(like):
		if(like[0].liked==1):
			learns.likes-=1
			learns.save()
			models.Learns_like.objects.filter(learn_id=learn_id,critisID=user.userName).update(liked=0)
		else:
			learns.likes+=1
			learns.save()
			models.Learns_like.objects.filter(learn_id=learn_id,critisID=user.userName).update(liked=1)
	else:
		learns.likes+=1
		learns.save()
		models.Learns_like.objects.create(critisID=user.userName,learn_id=learns.id,liked=1)
	comments = models.Comments_Learns.objects.filter(learn_id=learn_id)
	learns = models.Learns.objects.get(pk=learn_id)
	childcomments = models.ChildComments_Learns.objects.filter(learn_id=learn_id)
	return render(request, 'campus/content_learn.html',{'learns':learns,'comments':comments,'childcomments':childcomments})

#学习详情
def content_learn(request,learn_id):
	userId = request.session.get('userId',default=None)
	if userId:
		user = models.User.objects.get(pk=userId)
		learns =models.Learns.objects.get(pk=learn_id)
		comments = models.Comments_Learns.objects.filter(learn_id=learn_id)
		childcomments = models.ChildComments_Learns.objects.filter(learn_id=learn_id)
		return render(request, 'campus/content_learn.html',{'user':user,'learns':learns,'comments':comments,'childcomments':childcomments})
	else:
		return render(request, 'campus/login.html')
#评论学习
def comments_learn(request,learn_id):
	learns =models.Learns.objects.get(pk=learn_id)
	userId = request.session.get('userId',default=None)
	user = models.User.objects.get(pk=userId)
	content = request.POST.get('content','content')
	images = request.FILES.get('image')
	models.Comments_Learns.objects.create(critisID=user.userName,content=content,images=images,learn_id=learns.id)
	learns.counts+=1
	learns.save()
	comments = models.Comments_Learns.objects.filter(learn_id=learn_id)
	childcomments = models.ChildComments_Learns.objects.filter(learn_id=learn_id)
	return render(request, 'campus/content_learn.html',{'learns':learns,'comments':comments,'childcomments':childcomments})

#发表新闻事件
def show_published(request):
	userId = request.session.get('userId',default=None)
	if userId:
		user = models.User.objects.get(pk=userId)
		title = request.POST.get('title','title')
		content = request.POST.get('content','content')
		images = request.FILES.get('image')
		models.News.objects.create(publisher_id=user,publisher=user.userName,title=title,content=content,images=images,uid=userId)
		return redirect('/mycampus/index')
	else:
		return render(request, 'campus/login.html')
	
def published(request):
	userId = request.session.get('userId',default=None)
	if userId:
		return render(request, 'campus/published.html')
	else:
		return render(request, 'campus/login.html')
#显示表白墙
def love(request):
	userId = request.session.get('userId',default=None)
	if userId:
		loves = models.Lovewall.objects.order_by('-id')
		teasings = models.Teasingwall.objects.order_by('-id')
		return render(request, 'campus/love.html',{'loves':loves,'teasings':teasings})
	else:

mycampus/templates/campus/about_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width,initial-scale=1.0"/>
    <meta name="format-detection" content="telephone=no,email=no,date=no,address=no">
    <link rel="stylesheet" type="text/css" href="/static/css/aui.css" />
    <style type="text/css">
		header {
            margin-bottom: 15px;
            padding-top: 20px;
            position: fixed;
        }
        .aui-btn {
            margin-top: 15px;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
    <header class="aui-bar aui-bar-nav" id="header" >
        <div class="aui-pull-left">
            <i class="aui-iconfont aui-icon-left" onclick="closeWin();"></i>
        </div>
        <div class="aui-title">关于我们</div>
        <div class="aui-pull-right">
            <a class="aui-btn aui-iconfont aui-icon-refresh" href=""></a>
        </div>
    </header>
    <div id="header-bottom"></div>
    <div class="aui-text-center" id="header-logo">
        <img src="/static/image/demo2.png" />
    </div>
    <section class="aui-content-padded">
        <div class="aui-card-list">
            <div class="aui-card-list-header">
                校园微派客户端
            </div>
            <div class="aui-card-list-content-padded">
                <p>&nbsp;&nbsp;&nbsp;&nbsp;本客户端为校园微派的一个开源子项目，采用APICloud + AUI构建完成的，同时兼容iOS和Android设备。小歆记账AUI的数据部分存储在云端，与小歆记账WebApp数据共用，通过Ajax与小歆记账WebApp后台通信。其中AUI为前端框架，APICloud负责逻辑处理和云编译。</p>
                
            </div>
            <div class="aui-card-list-footer aui-text-center">
                702工作室 www.702.org
            </div>
        </div>
    </section>
    <div class="aui-content-padded aui-margin-b-15">
        <p><div class="aui-btn aui-btn-default aui-btn-block aui-btn-sm" onclick="closeWin();">返回</div></p>
    </div>
</body>
<script type="text/javascript" src="/static/js/api.js"></script>
<script type="text/javascript" src="/static/js/aui-toast.js" ></script>
<script type="text/javascript">
    var toast = new auiToast();
    apiready = function(){
        api.parseTapmode();
        //不支持沉浸式效果
        if (!api.statusBarAppearance) {
            $api.byId('header').style.paddingTop = 0;
        }
        //顶部导航栏高度抵消
        $api.byId('header-bottom').style.marginTop = $api.offset($api.byId('header')).h + 'px';

        //顶部Logo高度
        var logoHeight = (api.frameHeight / 6) + 'px';
        $api.byId('header-logo').style.height = logoHeight;
        $api.byId('header-logo').firstElementChild.style.height = logoHeight;
        
    }
    
    /** 关闭窗体 */
    function closeWin(){
        api.closeWin({
        });
    }

</script>
</html>

mycampus/templates/campus/test.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width,initial-scale=1.0"/>
    <meta name="format-detection" content="telephone=no,email=no,date=no,address=no">
    <title>我的</title>
    <link rel="icon" href="data:image/ico;base64,aWNv">
    <link rel="stylesheet" type="text/css" href="/static/css/aui.css" />
    <style type="text/css">
    	.aui-switch:checked {
            border-color: #212121;
            background-color: #212121;
        }
    </style>
</head>
<body>
	<header class="aui-bar aui-bar-nav" id="header" style="background-color: #27AE60;padding-top:12px; ">
        <div class="aui-title">我</div>
        <div class="aui-pull-right">
            <a class="aui-btn aui-iconfont aui-icon-refresh" href=""></a>
        </div>
    </header>
    <section class="aui-content aui-refresh-content aui-padded-t-15" style="padding-bottom: 50px;">
        <!-- 用户信息 -->
        <div class="aui-content aui-margin-b-15">
            <ul class="aui-list aui-media-list">
            	<a href="{% url 'mycampus:setting_information' %}">
	                <li class="aui-list-item aui-list-item-middle">
	                    <div class="aui-media-list-item-inner">
	                        <div class="aui-list-item-media" style="width: 3rem;">
		                            {% if user.userPicture %}
						                <img src="/static/{{user.userPicture}}" class="aui-list-img-sm aui-img-round" style="width: 48px;height: 48px;">
						            {% else %}
						                <img src="/static/user_img/default.jpg" class="aui-list-img-sm aui-img-round">
						            {% endif %}
	                        </div>
	                        <div class="aui-list-item-inner aui-list-item-arrow">
	                            <div class="aui-list-item-text">
	                                <div class="aui-list-item-title aui-font-size-18" id="id-username">{{user.userName}}</div>
	                            </div>
	                            <div class="aui-list-item-text aui-font-size-12">
	                                <span id="id-email">{{user.email}}</span>
	                            </div>
	                        </div>
	                    </div>
	                </li>
	            </a>
            </ul>
        </div>
        <div class="aui-content aui-margin-b-15">
            <ul class="aui-list aui-list-in">
               <a href="{% url 'mycampus:mypost' %}" style="color: #000">
                <li class="aui-list-item aui-list-item-middle">
                    <div class="aui-list-item-inner aui-list-item-arrow">
                        <div class="aui-list-item-title">我的发表</div>
                        <div class="aui-badge" style="position:relative;top:0; left:0;background-color: #27AE60"">{{count}}</div>
                    </div>
                </li>
               </a>
                <li class="aui-list-item aui-list-item-middle" onclick="openWin('class_win');">
                    <div class="aui-list-item-inner aui-list-item-arrow">
                        <div class="aui-list-item-title">我的关注</div>
                        <div class="aui-badge" style="position:relative;top:0; left:0">88</div>
                    </div>
                </li>
                <li class="aui-list-item aui-list-item-middle" onclick="openWin('calculator_win');">
                    <div class="aui-list-item-inner aui-list-item-arrow">
                        <div class="aui-list-item-title">我的粉丝</div>
                        <div class="aui-badge" style="position:relative;top:0; left:0">88</div>
                    </div>
                </li>
            </ul>
        </div>

        <!-- APP处理 -->
        <div class="aui-content aui-margin-b-15">
            <ul class="aui-list aui-list-in">
                <!-- 检查更新 -->
                <li class="aui-list-item aui-list-item-middle" onclick="cheakUpdata();">
                    <div class="aui-list-item-inner aui-list-item-arrow">
                        <div class="aui-list-item-title">检查更新</div>
                    </div>
                </li>
                <!-- 清除缓存 -->
                <li class="aui-list-item aui-list-item-middle" onclick="clearCache();">
                    <div class="aui-list-item-inner aui-list-item-arrow">
                        <div class="aui-list-item-title">清除缓存</div>
                        <div class="aui-list-item-right" id="id-cache-size">正在计算</div>
                    </div>
                </li>
                <!-- 关于我们 -->
                <li class="aui-list-item aui-list-item-middle" onclick="openWin();">
                    <div class="aui-list-item-inner aui-list-item-arrow">
                        <div class="aui-list-item-title">关于我们</div>
                    </div>
                </li>
            </ul>
            <p class="aui-list-item-text aui-font-size-12">
                &nbsp;&nbsp;&nbsp;&nbsp;当APP运行出现问题可以尝试清除缓存并重启应用。
            </p> 
        </div>
        <section class="aui-content aui-margin-b-15">
	        <ul class="aui-list aui-form-list">
	            <li class="aui-list-item" style="background-color: #fff">
	                <div class="aui-list-item-inner">
	                    <div class="aui-list-item-label">
	                        夜间模式
	                    </div>
	                    <div class="aui-list-item-input">
	                        <input type="checkbox" class="aui-switch" checked="">
	                    </div>
	                </div>
	            </li>
	        </ul>
	    </section>

        <!-- 退出登录 -->
        <a href="{% url 'mycampus:login_out' %}">
        <div class="aui-content aui-margin-b-15 aui-padded-l-10 aui-padded-r-10">
           <!-- <a href="{% url 'mycampus:login' %}" style="color: #fff" -->
            <div class="aui-btn aui-btn-danger aui-btn-block aui-btn-sm">
                退出登录
            </div>
           <!-- </a> -->
        </div>
        </a>
    </section>

    <footer class="aui-bar aui-bar-tab" id="footer" style="background-color: #27AE60">
        <div class="aui-bar-tab-item" tapmode>
            <i class="aui-iconfont aui-icon-home"></i>
            <div class="aui-bar-tab-label"><a href="{% url 'mycampus:index' %}" style="color: #000">首页</a></div>
        </div>
        <div class="aui-bar-tab-item" tapmode>
            <i class="aui-iconfont aui-icon-calendar"></i>
            <div class="aui-bar-tab-label"><a href="{% url 'mycampus:learn' %}" style="color: #000">学习</a></div>
        </div>
        <div class="aui-bar-tab-item" tapmode>
            <i class="aui-iconfont aui-icon-plus"></i>
            <div class="aui-bar-tab-label"><a href="{% url 'mycampus:published' %}" style="color: #000">发表</a></div>
        </div>
        <div class="aui-bar-tab-item" tapmode>
            <i class="aui-iconfont aui-icon-like"></i>
            <div class="aui-bar-tab-label"><a href="{% url 'mycampus:love' %}" style="color: #000">love</a></div>
        </div>
        <div class="aui-bar-tab-item aui-active" tapmode>
            <div class="aui-dot"></div>
            <i class="aui-iconfont aui-icon-my"></i>
            <div class="aui-bar-tab-label"><a href="" style="color: #000">我的</a></div>
        </div>
    </footer>

    <script type="text/javascript" src="/static/js/api.js" ></script>
    <script type="text/javascript" src="/static/js/jquery-2.1.1.min.js"></script>
    <!-- IOS兼容 -->
    <script type="text/javascript">
        apiready = function(){
                if(api.systemType == 'ios'){
                    scaleEnabled = true;
                    // document.getElementById('header').style.paddingTop = '10px';
                }
                //支持沉浸式效果
                if (!api.statusBarAppearance) {
                   document.getElementById('header').style.paddingTop = '0px';
                }
            };
    </script>
</body>
</html>